CREATE_USER_QUERY = """
    CREATE TABLE telegarm_users(
    ID INTEGER PRIMARY KEY,
    TELEGRAM_ID INTEGER,
    USERNAME CHAR(50),
    FIRST_NAME CHAR(50),
    LAST_NAME CHAR(50),
    UNIQUE (TELEGRAM_ID)
)
"""

INSERT_USER_QUERY = """
    INSERT OR IGNORE INTO telegarm_users VALUES (?, ?, ?, ?, ?)
"""